[package]
name = "haijin_loser"
version = "0.1.0"
edition = "2021"
authors = ["haijin"]
description = "一个失败者的rust项目"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
